module.exports = [
  {
    name: "Nicolas",
    last_name: "Morales Romero",
    image: "/images/Hombre.jpg",
    birthdate: "21/04/2021",
    description: "soy el mejor del Front",
    password: "Admin@123",
    email: "nicomorales@gmail.com",
    tel: "2244446245",
    Instagram: "",
    sexo: "MASCULINO",
    professionId: "20",
  },
  {
    name: "Jose",
    last_name: "Sat",
    image: "/images/Hombre.jpg",
    birthdate: "21/04/2021",
    description: "soy el mejor QA",
    password: "Admin@123",
    email: "josesat@gmail.com",
    tel: "2244446245",
    Instagram: "",
    sexo: "MASCULINO",
    professionId: "18",
  },
  {
    name: "cristofer",
    last_name: "crego",
    image: "/images/Hombre.jpg",
    birthdate: "21/04/2021",
    description: "soy el mejor del back",
    password: "Admin@123",
    email: "kiki@gmail.com",
    tel: "2244446245",
    Instagram: "",
    sexo: "MASCULINO",
    professionId: "14",
  },
  {
    name: "maria",
    last_name: "pereira",
    image: "/images/Mujer.jpg",
    birthdate: "21/04/2021",
    description: "soy la mejor del front",
    password: "Admin@123",
    email: "mariapereira@gmail.com",
    tel: "2244446245",
    Instagram: "",
    sexo: "FEMENINO",
    professionId: "15",
  },
  {
    name: "malinda",
    last_name: "perez",
    image: "/images/Mujer.jpg",
    birthdate: "21/04/2021",
    description: "soy la mejor QA",
    password: "Admin@123",
    email: "malindaperez@gmail.com",
    tel: "2244446245",
    Instagram: "",
    sexo: "FEMENINO",
    professionId: "11",
  },
  {
    name: "lautaro",
    last_name: "miceli",
    image: "/images/Hombre.jpg",
    birthdate: "21/04/2021",
    description: "soy el mejor del front",
    password: "Admin@123",
    email: "laumiceli@gmail.com",
    tel: "2244446245",
    Instagram: "",
    sexo: "MASCULINO",
    professionId: "10",
  },
  {
    name: "franco",
    last_name: "huayller",
    image: "/images/Hombre.jpg",
    birthdate: "21/04/2021",
    description: "soy el mejor del back",
    password: "Admin@123",
    email: "franhuayller@gmail.com",
    tel: "2244446245",
    Instagram: "",
    sexo: "MASCULINO",
    professionId: "10",
  },
];
